//! Pinned release of the prebuilt native openDAQ libraries.
//!
//! Regenerated by the `build-native-binaries` GitHub Actions workflow -- do not
//! edit by hand.  The archives carry the openDAQ core libraries, the flat C
//! bindings library (`copendaq`), and the reference device / function block /
//! streaming modules, built from the pinned openDAQ commit below.

#![allow(dead_code)] // the repo/ref/sha constants document the pinned build

pub const TAG: &str = "binaries-20260709-869cb62";
pub const BASE_URL: &str =
    "https://github.com/mihoci10/opendaq-rs/releases/download/binaries-20260709-869cb62/";
pub const OPENDAQ_REPO: &str = "https://github.com/adolenc/openDAQ.git";
pub const OPENDAQ_REF: &str = "c-bindings-docstrings";
pub const OPENDAQ_SHA: &str = "869cb62b1e0bb18aa61e8dad3d4812bcce76be36";

/// (platform directory name, archive file name, SHA-256 of the archive)
pub const ARCHIVES: &[(&str, &str, &str)] = &[
    (
        "linux-x64",
        "opendaq-bin-linux-x64.tar.gz",
        "466a55d6a9617212c264e712526e68530ebfc0d01adad6f0140eac6684e2b5a8",
    ),
    (
        "darwin-arm64",
        "opendaq-bin-darwin-arm64.tar.gz",
        "3d70a422d884c488e5ec7cb5bd39624109caa8521e1e749cca0ce530af251cf5",
    ),
    (
        "windows-x64",
        "opendaq-bin-windows-x64.tar.gz",
        "9763c088274891222f16914417ccec1a390097b2cef3d1269362cc0d335a502f",
    ),
];
